config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cosplays do
    resources :bookings, only: [ :show, :new, :create ]
  end
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :cosplay

  validates :date, presence: true
end

app/models/cosplay.rb
class Cosplay < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  # price to be positive
  validates :price, presence: true,
                    format: { with: /\A\d+(\.\d{1,2})?\z/, message: "Invalid price format." }
  # details to be between 6 and 255 characters long
  validates :details, presence: true, length: { in: 6..500 }
  validates :title, presence: true, length: { in: 3..50 }
  validates :photo, presence: true
  # ,
  #                   format: { with: /.+\.(png|jpg|jpeg)\z/,
  #                             message: 'Invalid photo format. Only .png, .jpg and .jpeg extensions are allowed.' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cosplays, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  has_many :booked_cosplays, through: :bookings, source: :cosplay

  validates :first_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true, length: { minimum: 2 }
  validates :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show; end

  def new
    @booking = Booking.new
    @cosplay = Cosplay.find(params[:cosplay_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @cosplay = Cosplay.find(params[:cosplay_id])
    @booking.cosplay = @cosplay
    @booking.user = current_user
    if @booking.save
      flash[:success] = "Your booking was created."
      redirect_to dashboard_path
    else
      render :new
      flash[:warning] = "Your booking was not created"
    end
  end

  # def destroy
  #   @booking.destroy
  #   flash[:warning] = "Your booking has been deleted."
  # end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/cosplays_controller.rb
class CosplaysController < ApplicationController
  before_action :set_cosplay, only: %i[show edit update destroy]

  def index
    @cosplays = Cosplay.all
  end

  def show; end

  def new
    @cosplay = Cosplay.new
  end

  def create
    @cosplay = Cosplay.new(cosplay_params)
    @cosplay.user = current_user
    if @cosplay.save
      redirect_to cosplay_path(@cosplay)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cosplay.update(cosplay_params)
      redirect_to cosplay_path(@cosplay), notice: 'Your listing was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cosplay.destroy
    redirect_to cosplays_path, notice: 'Your listing was successfully destroyed'
  end

  private

  def cosplay_params
    params.require(:cosplay).permit(:user_id, :price, :details, :photo, :title)
  end

  def set_cosplay
    @cosplay = Cosplay.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= link_to cosplays_path do %>
  <i class="fas fa-solid fa-angle-left my-3 btn btn-primary"> Back</i>
<% end %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
        <%= simple_form_for([@cosplay, @booking]) do  |f| %>
          <%= f.input :date %>
          <%= f.button :submit %>
        <% end %>
    </div>
  </div>
</div>

app/views/cosplays/edit.html.erb
<h1>Edit your cosplay listing</h1>

<%= simple_form_for(@cosplay) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price, as: :string %>
  <%= f.button :submit, class: 'btn-flat' %>
<% end %>

app/views/cosplays/index.html.erb
<div id="cosplay-index-top">
  <h1>Cosplays Available</h1>
  <%= link_to new_cosplay_path do %>
    <i class="fas fa-solid fa-plus my-1 py-2 px-2 btn-flat"> Become a cosplayer</i>
  <% end %>
</div>
<br>
<div class="index-cards">
  <% @cosplays&.each do |c| %>
    <%= link_to cosplay_path(c), class: 'card-trip' do %>
      <% if c.photo.key %>
        <%= cl_image_tag(c.photo.key) %>
      <% else %>
        <%= cl_image_tag '' %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2> <%= c.title  %></h2>
        </div>
        <h2 class="card-trip-pricing">€ <%= c.price %> </h2>
        <% if c.user.photo.key %>
          <%= cl_image_tag(c.user.photo.key, :class => "card-trip-user avatar-bordered") %>
        <% else %>
          <%= cl_image_tag '' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cosplays/new.html.erb
<h1>Create your cosplay listing</h1>

<%= simple_form_for(@cosplay) do |f| %>
    <%= f.input :title, placeholder: 'What is your costume?' %>
    <%= f.input :details, placeholder: 'Short description of your coslplay...' %>
    <%= f.input :photo, as: :file %>
    <%= f.input :price, as: :string, placeholder: 'e.g. 59.99' %>
    <%= f.button :submit, class: 'btn-flat' %>
  <% end %>

app/views/cosplays/show.html.erb
<%= link_to cosplays_path do %>
  <i class="fas fa-solid fa-angle-left my-3 btn btn-primary"> Back</i>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-6" id="cosplay_image">
      <% if @cosplay.photo.key %>
        <%= cl_image_tag(@cosplay.photo.key) %>
      <% end %>
    </div>
    <div class="col-sm-6">

      <h1><%= @cosplay.title %></h1><br>
        <h4><%= @cosplay.user.first_name %> <%= @cosplay.user.last_name %></h4>
        <p><i class="fas fa-solid fa-info"></i> <%= @cosplay.details %></p>
        <p><i class="fas fa-solid fa-euro-sign"> </i> <%= @cosplay.price %></p><br><br>
        <% unless current_user == @cosplay.user %>
          <%= link_to "Book now", new_cosplay_booking_path(@cosplay), class: "btn btn-flat" %>
        <% end %>
        <br>
        <% if current_user == @cosplay.user %>
          <span><%= link_to 'Edit', edit_cosplay_path(@cosplay) %></span> |
          <span><%= link_to 'Delete listing', @cosplay, method: :delete, data: { confirm: 'Are you sure you want to delete this listing?'} %></span>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>CosplayMunich782</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <div class="container"><%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <footer class="container">
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Your booked cosplays</h1>
<% current_user.bookings.each do |booking| %>
<div class="d-flex justify-content-center">
  <div class="row d-flex dashboard-card col-6">
    <div class="container col-6"><p>
      <h1><%= booking.cosplay.title %></h1>
        <p>Owner: <%= booking.cosplay.user.first_name %> <%= booking.cosplay.user.last_name %></p>
        <p>Price: <%= booking.cosplay.price %>€</p>
        <p>Details: <%= booking.cosplay.details %></p>
        <p>Date: <%= booking.date %> </p>
      </div>
        <div class="container col-6">
          <%= cl_image_tag(booking.cosplay.photo.key,
                width: 250, crop: :fill) %>
        </div>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0)), url(<%=asset_path 'cosplay-banner-cropped.jpg'  %>)">
  <div class="container">
    <h1 id="home-title">Rent a <strong>cosplayer</strong></h1>
    <p>Meet your favourite characters!</p>
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" placeholder="Batman, Jack Sparrow..." name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-primary">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
    <% end %>
  </div>
</div>
<div class="container">
  <p class="text-center" id="definition">Hire a <strong>costume player</strong> for parties, promotions or any other event! Our recommendations:</p>
</div>
<div class="cards ">
  <a href="/cosplays" text-decoration: none>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=asset_path 'superheroes.jpg'  %>)">
    Superheroes
</div>
</a>
<a href="/cosplays">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=asset_path 'disney.png'  %>)">
    Disney characters
  </div>
</a>

<a href= "/cosplays">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=asset_path 'popular.jpg'  %>)">
    Most popular
  </div>
</a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" class="d-flex flex-column min-vh-100">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Batch #782, Munich
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dp3tpzhjx/image/upload/v1645786314/cosplay_avatars/93438317_jmgmix.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "View bookings", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Become a cosplayer", new_cosplay_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>